### ISSUE TITLE
T.H - Reconnection to ZCC

### ISSUE THREAD

**Issue by TommyAUS88** [markhannon/zimi-integration#10]
Logger: ControlPoint
Source: custom_components/zimi/cover.py:84
Integration: zimi
First occurred: 3:07:05 PM (38 occurrences)
Last logged: 3:33:29 PM

Controller not ready to accept commands - attempting to re-connect
Existing socket closed
Socket error when connecting to ZCC 192.168.2.40:5003
Re-connection to ZCC failed with ControlPointError: Socket error when connecting to ZCC 192.168.2.40:5003 - will retry in 90

**Comment by markhannon** [comment]
Please try version 1.3rc8 of integration.   (Need to tick allow pre-release in HACS)
