### ISSUE TITLE
Second output on 2 port switch is not controllable from Home Assistant

### ISSUE THREAD

**Issue by markhannon** [markhannon/zimi-integration#14]
New HA install with all devices up and running except the second port on all 2 port switches is not controllable.

Sending a turn on command from the HA webpage does not work, sending a turn on command from the HA webpage for the first port on all of these switches works.

The problem is the same on all 9 2 port switches installed.

**Comment by markhannon** [comment]
Fixed with zcc upgrade

**Comment by Picco-10** [comment]
Hello, 
i am having this issue on my HA instance, running version 1.4.0. zcc firmware vers 2023081010011. i have deleted the zimi integration and reloaded to no avail. any assistance would be greatly appriciated

**Comment by markhannon** [comment]
Can you send your ZCC mac details please?   We will need the zimi guys to restart it remotely - that's what fixed for me

**Comment by Picco-10** [comment]
Thanks for the reply, please see pic of MACSent from my iPhoneOn 25 Mar 2024, at 07:57, markhannon ***@***.***> wrote:﻿
Can you send your ZCC mac details please?   We will need the zimi guys to restart it remotely - that's what fixed for me

**Comment by markhannon** [comment]
no picture received

**Comment by Picco-10** [comment]
MAC4C 24 98 44 4F 3DThanksSent from my iPhoneOn 25 Mar 2024, at 09:46, markhannon ***@***.***> wrote:﻿
no picture received

**Comment by markhannon** [comment]
Hi, I need the bluethooth MAC, the one starting with C4FFBC

**Comment by Picco-10** [comment]
No worriesC4FFBC90C023Thanks Sent from my iPhoneOn 25 Mar 2024, at 14:28, markhannon ***@***.***> wrote:﻿
Hi, I need the bluethooth MAC, the one starting with C4FFBC

**Comment by markhannon** [comment]
It should be fixed on your unit now – please test.   (The zimi team pushed an updated firmware to your zcc)

From: Picco-10 ***@***.***>
Date: Monday, 25 March 2024 at 16:25
To: markhannon/zimi-integration ***@***.***>
Cc: markhannon ***@***.***>, State change ***@***.***>
Subject: Re: [markhannon/zimi-integration] Second output on 2 port switch is not controllable from Home Assistant (Issue #14)
No worriesC4FFBC90C023Thanks Sent from my iPhoneOn 25 Mar 2024, at 14:28, markhannon ***@***.***> wrote:﻿
Hi, I need the bluethooth MAC, the one starting with C4FFBC

**Comment by Picco-10** [comment]
All sorted, thanks for your helpSent from my iPhoneOn 25 Mar 2024, at 16:21, markhannon ***@***.***> wrote:﻿
It should be fixed on your unit now – please test.   (The zimi team pushed an updated firmware to your zcc)



From: Picco-10 ***@***.***>

Date: Monday, 25 March 2024 at 16:25

To: markhannon/zimi-integration ***@***.***>

Cc: markhannon ***@***.***>, State change ***@***.***>

Subject: Re: [markhannon/zimi-integration] Second output on 2 port switch is not controllable from Home Assistant (Issue #14)

No worriesC4FFBC90C023Thanks Sent from my iPhoneOn 25 Mar 2024, at 14:28, markhannon ***@***.***> wrote:﻿

Hi, I need the bluethooth MAC, the one starting with C4FFBC

**Comment by kxwebster** [comment]
Just comment to let you know how much I appreciate this HA integration. My most used function is automating the shower exhaust fan linked to a ruuvi-tag humidity sensor. Humidity in bathrooms can be a nuisance in Tassie.

**Comment by markhannon** [comment]
Thanks for letting us know.   Nice to hear it is useful

Regards, Mark
________________________________
