### ISSUE TITLE
Light Color Modes not supported

### ISSUE THREAD

**Issue by Redxd** [markhannon/zimi-integration#23]
I think this error is associated with the single light switch and fan controller. I've also got a double power point configured.

WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.zimi.light.ZimiLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'zimi' custom integration

**Comment by markhannon** [comment]
Fixed in version 1.4.3-dev2 and later
