### ISSUE TITLE
Garage Door deprecated feature

### ISSUE THREAD

**Issue by Redxd** [markhannon/zimi-integration#24]
It looks like this was coming from my garage door controller which I had integrated into the Zimi app but it hasn't been installed/online since moving house.

WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.zimi.cover.ZimiCover'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CoverEntityFeature.OPEN|CLOSE|SET_POSITION|STOP: 15>, please report it to the author of the 'zimi' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by markhannon** [comment]
Fixed in all versions from 1.4.1 and later.   (Set to accept pre-release if you want them)
