### ISSUE TITLE
Fan states

### ISSUE THREAD

**Issue by Redxd** [markhannon/zimi-integration#25]
This is associated with my light/fan wall controller. 

WARNING (MainThread) [homeassistant.components.fan] Entity None (<class 'custom_components.zimi.fan.ZimiFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please report it to the author of the 'zimi' custom integration
WARNING (MainThread) [homeassistant.components.fan] Entity None (<class 'custom_components.zimi.fan.ZimiFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please report it to the author of the 'zimi' custom integration

**Comment by markhannon** [comment]
FIxed in version 1.4.3-dev2
