### ISSUE TITLE
Opening garage results in repeated door openings until HA restart

### ISSUE THREAD

**Issue by teleksterling** [markhannon/zimi-integration#3]
Finally getting around to logging this issue!

Changes to my garage door state and attributes (e.g. for position) never update in HA.

When I issue a close or open command, there is a delay (~10s) and then the action is carried out successfully - but the state doesn't change in HA. 

I think this then triggers a retry in the integration because it assumes the command failed!

This had the effect of me fighting my garage door to stay closed - me with the remote vs Home Assistant with the API. Once i figured out this was the cause, I just stopped using HA to move the door instead using the Zimi app.

Is it just me?

**Comment by markhannon** [comment]
I must confessI haven't looked at this code or solution for a year.   Let me check with Anthony who is actually using HA and Zimi.

**Comment by markhannon** [comment]
Anthony will check - he says that it works for his garage door open/closed but isn't sure about partial states. 

Can you upload the logs?   You might need to increase the debug level.

Can you also setup a port-forward and firewall to open the zcc port to me?   If so I can do a remote debug session with you from a local HA instance.   This is how I built the basic integration using Anthony's home and all the lights/doors/switches as a test bed.   I would need you onsite and monitoring the door while I test of course!

**Comment by markhannon** [comment]
Anthony tried this today.   He sent me a video of the UI state changing as the door opened.   

Can we arrange a time for some debug?
