### ISSUE TITLE
Garage Door Disconnects

### ISSUE THREAD

**Issue by copytec11** [markhannon/zimi-integration#8]
Logger: ControlPoint
Source: custom_components/zimi/cover.py:132
Integration: zimi
First occurred: 9:05:08 AM (4 occurrences)
Last logged: 9:05:11 AM

Controller not ready to accept commands - attempting to re-connect
Existing socket closed
Socket error when connecting to ZCC 192.168.2.40:5003
Re-connection to ZCC failed with ControlPointError: Socket error when connecting to ZCC 192.168.2.40:5003 - will retry in 90

This error originated from a custom integration.

Logger: ControlPointSocket
Source: custom_components/zimi/cover.py:132
Integration: zimi
First occurred: 9:05:11 AM (1 occurrences)
Last logged: 9:05:11 AM

Connection received socket timed out error from 192.168.2.40:5003

**Comment by markhannon** [comment]
Please try version 1.3rc8 of integration.   (Need to tick allow pre-release in HACS)

**Comment by markhannon** [comment]
Version 1.3.2 of integration should improve
